
spring:
  application:
    name: SpringBoot-Kafka-Producer

server:
  port: 8084

kafka:
  brokerAddress: localhost:29092
  schemaRegistryAddress: http://localhost:8081
  topics:
    user:
      name: user-topic
    company:
      name: company-topic
    message:
      name: message-topic