
spring:
  application:
    name: SpringBoot-Kafka-Producer

server:
  port: 8080

kafka:
  brokerAddress: localhost:9093
  schemaRegistryAddress: localhost:8081
  sasl-username: your_sasl_username
  sasl-password: your_sasl_password
  topics:
    user:
      name: user-topic
      group: userTopicGroup
    company:
      name: company-topic
      group: companyTopicGroup
    message:
      name: message-topic
      group: messageTopicGroup